### PR TITLE
Guards against a set on destroyed error

### LINKED ISSUE #271: Writing some tests?
Howdy, was looking this addon over and noticed that there aren't many tests. Think that'd be something we should add here over time?

### PR DESCRIPTION
**Pull request by acorncom**
Fixes #271 (or at least starts to 😉 )

### CODE REVIEW

**Comment by acorncom** [comment]
Looks like tests haven't been setup to run on this repo yet (either with Travis or Github Actions). Happy to help do that if it would be useful

**Comment by ttill** [comment]
Thanks for your contributions, David! I just did set up a CI pipeline using Travis.

**Comment by acorncom** [comment]
Thanks @ttill Did you happen to do a new NPM release as well? Would love to pull in the new work

**Comment by ttill** [comment]
Released as 0.3.7. Thanks for reminding me.

**Pull request merged**
